### ISSUE TITLE
state.cgi mit device_id - unvollständige Ausgabe beim Aufruf mit curl von der commandline

### ISSUE THREAD

**Issue by ghost** [hobbyquaker/XML-API#91]
Homematic CCU2: Firmware: 2.61.7
XML-API: 2.3

wenn ich einen state einers devices im browser aufrufe erhalte ich die vollständige ausgabe:

http://MYCCU2/addons/xmlapi/state.cgi?sid=xxxMYLOVELYTOKENxxx&device_id=19604
![homematic_ccu_xml_state](https://github.com/homematic-community/XML-API/assets/25220590/74832b97-c430-41ae-a732-28415610a21c)

rufe ich allerdings von der commandline die state.cgi mit einer device_id auf bekomme ich lediglich:
```
curl http://MYCCU2/addons/xmlapi/state.cgi?sid=xxxMYLOVELYTOKENxxx&device_id=19604

[1] 31960
<?xml version='1.0' encoding='ISO-8859-1' ?><state></state>
[1]+  Fertig              
```

**Comment by jens-maus** [comment]
> rufe ich allerdings von der commandline die state.cgi mit einer device_id auf bekomme ich lediglich:
> 
> ```
> curl http://MYCCU2/addons/xmlapi/state.cgi?sid=xxxMYLOVELYTOKENxxx&device_id=19604
> 
> [1] 31960
> <?xml version='1.0' encoding='ISO-8859-1' ?><state></state>
> [1]+  Fertig              
> ```

Ist doch auch klar, denn du setzt die URL ja auch nicht in Anführungszeichen damit das "&" in der URL nicht fälschlichweise von der Unix shell als ein operator interpretiert wird.

Ergo, falscher aufruf. Das gehört so geregelt:

```
curl "http://MYCCU2/addons/xmlapi/state.cgi?sid=xxxMYLOVELYTOKENxxx&device_id=19604"
```
